import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { useState, useEffect } from 'react';
import axios from 'axios';


export default function Home() {
  const [trips, setTrips] = useState([]);
  const [title, setTitle] = useState("");
  const [location, setLocation] = useState("");
  const [content, setContent] = useState("");

  useEffect(() => {
    axios.get('/api/trips')
      .then(response => {
        setTrips(response.data);
      })
      .catch(error => {
        console.error(error);
      });
  }, []);

  const handleSubmit = async (e) => {
    e.preventDefault();
    const newTrip = {
      title,
      location,
      content,
    };
    const res = await axios.post("/api/trips", newTrip);
    setTrips(prevTrips => [...prevTrips, res.data]); // Add new trip to existing trips
    setTitle(""); // Reset form state after successful submission
    setLocation("");
    setContent("");
  };
  

  useEffect(() => {
    axios.get('/api/trips/[tripid]/comments')
      .then(response => {
        setComment(response.data);
      })
      .catch(error => {
        console.error(error);
      });
  }, []);

  const handleComment = async (e, trip, comment) => {
    e.preventDefault();
    try {
      const response = await axios.post(`/api/trips/${tripid}/comments`, {
        content,
      });
      console.log(response.data);
      // Reset form state after successful submission
      setContent("");
    } catch (error) {
      console.error(error);
    }
  };


  return (
    <>
      <Head>
        <title>dont trip.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <img src='/logo.png' />
        <div className={styles.slogan}>Post your crazy travel ideas and get honest opinions from those who have travelled the globe.</div>
        <div>
          <h1>Post a trip idea</h1>

          <form onSubmit={handleSubmit} className={styles.formContainer}>
            <label>
              Trip Title:
              <input type="text" value={title} onChange={(e) => setTitle(e.target.value)} />
            </label>
            <label>
              Location:
              <input type="text" value={location} onChange={(e) => setLocation(e.target.value)} />
            </label>
            <label>
              Details:
              <input type="text" value={content} onChange={(e) => setContent(e.target.value)} />
            </label>
            <button type="submit">Create Trip</button>
          </form>

          <hr />
          <h1>All trip posts</h1>
          {trips.map(trip => (
            <TripComp key={trip.id} trip={trip} handleComment={handleComment} />
          ))}
        </div>
      </main>
    </>
  )
}




function TripComp({trip, handleComment}) {
  const [comment, setComment] = useState("");
  const [comments, setComments] = useState([]);

  useEffect(() => {
    axios.get(`/api/trips/${trip.id}/comments`)
      .then(response => {
        setComments(response.data);
      })
      .catch(error => {
        console.error(error);
      });
  }, [trip.id]);

  return (
    <div className={styles.tripContainer}>
      <div className={styles.postContainer}>
        <h2 className={styles.tripTitle}>{trip.title} <b>📍{trip.location}</b></h2>
        <p className={styles.tripContent}>{trip.content}</p>
      </div>
      <form onSubmit={(e) => {
        e.preventDefault()
        handleComment(e, trip, comment)
      }}>
        <label>
          Comment:
          <textarea className={styles.commentInput} value={comment} onChange={(e) => setComment(e.target.value)} />
        </label>
        <button className={styles.commentButton} type="submit">Submit</button>
      </form>
      <ul className={styles.commentList}>
        {comments.map(comment => (
          <li key={comment.id} className={styles.commentItem}>- {comment.content}</li>
        ))}
      </ul>
    </div>
  );
}
